#! /bin/bash

set -e

if [ -t 1 ]; then
    SCRIPT_NAME="bootstrap:\033[33m"
    LINE_END="\033[0m"
else
    SCRIPT_NAME="bootstrap:"
    LINE_END=""
fi

NINJA=ninja
NINJA_VERSION=1.3.4

if [ ! -f $NINJA ] || [ $($NINJA --version) != $NINJA_VERSION ]; then

    echo -e "$SCRIPT_NAME downloading ninja...$LINE_END"
    if [ -d "ninja-build" ]; then
        rm -rf ninja-build
    fi
    git clone git://github.com/martine/ninja.git ninja-build && cd ninja-build
    git checkout -q v1.3.4

    echo -e "$SCRIPT_NAME building ninja...$LINE_END"
    ./bootstrap.py
    cd ..
    mkdir -p .build
    cp ninja-build/ninja $NINJA
    rm -rf ninja-build

else
    echo -e "$SCRIPT_NAME already got ninja, skipping.$LINE_END"
fi

